import Art from '../components/Art';import Icon from '../components/Icon';import {usePlayer,useTime,fmt,statusLabel} from '../hooks/usePlayer';import {tracks} from '../data';import {useReveal} from '../hooks/useReveal';import {useParallax} from '../hooks/useParallax';
export default function Featured(){const p=usePlayer(),tm=useTime(),k=tracks[0],on=p.i===0,d=on&&tm.dur?tm.dur:k.dur,pr=on?Math.min(1,tm.t/d):0,msg=!k.src?'Preview unavailable':on?statusLabel(p.status):null,ref=useReveal<HTMLDivElement>(),bpm=useParallax<HTMLSpanElement>(-.07);
return <section id="player" className="relative overflow-hidden px-6 py-32 md:px-12 md:py-44">
<div aria-hidden className="pointer-events-none absolute -left-1/4 top-0 h-full w-3/4" style={{background:'radial-gradient(closest-side,rgb(var(--accent) / var(--halo-a)),transparent)'}}/>
<div ref={ref} className="reveal relative mx-auto grid max-w-[1600px] items-center gap-14 lg:grid-cols-12">
<div className="relative lg:col-span-6"><Art a={k.a} b={k.b} image={k.image} className="aspect-square w-full lg:w-[88%]"/>
<span ref={bpm} aria-hidden className="pointer-events-none absolute -bottom-6 left-4 font-display text-[clamp(4rem,12vw,11rem)] font-extrabold leading-none tracking-[-.04em] text-white mix-blend-difference lg:left-[40%]">{k.bpm}</span></div>
<div className="lg:col-span-5 lg:col-start-8"><p className="text-sm text-bone/60">Featured release</p>
<h2 className="mt-4 font-display text-5xl font-extrabold leading-[.92] tracking-[-.03em] md:text-7xl">{k.title}</h2><p className="mt-4 text-xl text-bone/80">{k.artist}</p>
<dl className="mt-8 grid max-w-md grid-cols-3 gap-6 border-t border-bone/15 pt-6">{[['Genre',k.genre],['BPM',k.bpm],['Released',k.date]].map(([a,b])=><div key={a}><dt className="text-xs text-bone/60">{a}</dt><dd className="mt-1 text-sm">{b}</dd></div>)}</dl>
<div className="mt-10 flex w-full min-w-0 max-w-full items-center gap-3 overflow-hidden sm:gap-6"><button aria-label={on&&p.playing?'Pause':'Play'} onClick={()=>on?p.toggle():p.play(0)} className="relative grid h-14 w-14 shrink-0 place-items-center transition duration-500 hover:scale-105 sm:h-20 sm:w-20">
<svg viewBox="0 0 80 80" className="absolute inset-0 -rotate-90"><circle cx="40" cy="40" r="38" fill="none" className="stroke-bone/15"/><circle cx="40" cy="40" r="38" fill="none" className="stroke-cyan" strokeWidth="2" strokeDasharray={239} strokeDashoffset={239*(1-pr)}/></svg><Icon n={on&&p.playing?'pause':'play'} s={22}/></button>
<div className="min-w-0 flex-1"><div className="relative flex h-14 items-center gap-[3px]">{Array.from({length:48},(_,i)=>{const h=18+Math.abs(Math.sin(i*.7)*Math.cos(i*.23))*82;return <i key={i} aria-hidden className="w-full rounded-full transition-colors duration-300" style={{height:`${h}%`,background:i/48<pr?'rgb(var(--accent))':'rgb(var(--fg) / .22)'}}/>})}
<input aria-label="Seek featured track" disabled={!on||!k.src||!tm.dur} type="range" min={0} max={d} step="any" value={on?tm.t:0} onChange={e=>p.seek(+e.target.value)} className="absolute inset-0 h-full w-full min-w-0 cursor-pointer opacity-0 disabled:cursor-default"/></div>
<div className="mt-2 flex justify-between text-xs tabular-nums text-bone/60"><span>{fmt(on?tm.t:0)}</span>{msg&&<span role="status" className="text-cyan">{msg}</span>}<span>{fmt(d)}</span></div></div></div></div></div></section>}
