import AmbientWave from '../components/AmbientWave';import {useState} from 'react';import {site} from '../data';import Logo from '../components/Logo';
const nav=[['Music','#music'],['Artists','#artists'],['About','#about'],['Events','#events'],['Stories','#stories'],['Contact',site.contact]];
export default function Footer(){const [msg,setMsg]=useState('');
const sub=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget;if(!site.newsletterUrl)return setMsg('Signup is not connected yet. Set site.newsletterUrl in src/data/site.ts.');
try{const r=await fetch(site.newsletterUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:new FormData(f).get('email')})});if(!r.ok)throw 0;setMsg('You are on the list.');f.reset()}catch{setMsg('Something went wrong. Please try again.')}};
return <footer className="relative px-6 pb-32 pt-24 md:px-12"><AmbientWave className="-top-12"/><div className="grid gap-12 border-t border-bone/15 pt-16 lg:grid-cols-2"><div>
<h2 className="font-display text-4xl font-extrabold tracking-[-.03em] md:text-6xl">STAY IN THE FREQUENCY</h2><p className="mt-4 text-bone/60">Get new releases, exclusive sounds and upcoming events.</p>
<form onSubmit={sub} className="mt-8 flex max-w-md border-b border-bone/30 focus-within:border-cyan"><label className="sr-only" htmlFor="em">Email</label><input id="em" name="email" type="email" required placeholder="Your email" className="w-full bg-transparent py-3 outline-none placeholder:text-bone/60"/><button className="text-sm font-semibold tracking-widest">JOIN</button></form><p role="status" className="mt-3 min-h-5 text-sm text-bone/75">{msg}</p></div>
<div className="grid grid-cols-2 gap-8 text-sm"><nav aria-label="Footer"><ul className="space-y-3">{nav.map(([n,h])=><li key={n}><a href={h} className="text-bone/75 hover:text-bone">{n}</a></li>)}</ul></nav>
<ul className="space-y-3">{site.socials.map(s=><li key={s.name}>{s.url?<a href={s.url} target="_blank" rel="noopener noreferrer" className="text-bone/75 hover:text-bone">{s.name}</a>:<span className="text-bone/60" title="Link coming soon">{s.name}</span>}</li>)}</ul></div></div>
<div className="mt-20 flex flex-wrap items-end justify-between gap-6 border-t border-bone/15 pt-10"><a href="#top" aria-label={`${site.brand.name} home`}><Logo className="h-12 md:h-16"/></a><p className="text-xs text-bone/60">© 2026 {site.brand.name}. All rights reserved.</p></div></footer>}
