import RevealText from '../components/RevealText';import AmbientWave from '../components/AmbientWave';import Art from '../components/Art';import Icon,{Eq} from '../components/Icon';import {tracks} from '../data';import {usePlayer,fmt} from '../hooks/usePlayer';
export default function Releases(){const p=usePlayer();const lit=(e:React.PointerEvent<HTMLElement>)=>{if(e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect(),s=e.currentTarget.style;s.setProperty('--px',String((e.clientX-r.left)/r.width));s.setProperty('--py',String((e.clientY-r.top)/r.height))};
return <section id="music" className="relative py-28 md:py-40"><AmbientWave className="-top-12"/><div className="flex items-end justify-between px-6 md:px-12"><RevealText as="h2" className="font-display text-5xl font-extrabold leading-[.9] tracking-[-.03em] md:text-7xl" lines={['LATEST', 'RELEASES']}/><p className="hidden max-w-[14rem] text-sm text-bone/60 md:block">Newest first. Select a release to play.</p></div>
<ul className="mt-14 flex snap-x gap-6 overflow-x-auto px-6 pb-10 md:px-12 [scrollbar-width:none]">{tracks.map((t,i)=>{const sel=p.i===i,cur=sel&&p.playing;return <li key={t.id} data-sel={sel} className={`group w-[72vw] max-w-[360px] shrink-0 snap-start md:w-[22vw] md:min-w-[280px] ${i%2?'md:mt-14':''}`}>
<button onClick={()=>cur?p.toggle():p.play(i)} aria-label={`${cur?'Pause':'Play'} ${t.title} by ${t.artist}`} aria-pressed={cur} onPointerMove={lit} className="tilt relative block w-full overflow-hidden text-left transition-shadow duration-700 group-hover:shadow-[0_30px_80px_-30px_var(--card-glow)] group-data-[sel=true]:shadow-[0_30px_80px_-30px_var(--card-glow-sel)]">
<Art a={t.a} b={t.b} image={t.image} className="aspect-[4/5] w-full transition duration-[1200ms] ease-out group-hover:scale-[1.04] group-hover:brightness-125"/><span aria-hidden className="pointer-events-none absolute inset-0 opacity-0 transition-opacity duration-500 group-hover:opacity-100" style={{background:'radial-gradient(220px circle at calc(var(--px,.5)*100%) calc(var(--py,.5)*100%),rgb(var(--accent2) / .3),transparent 65%)'}}/>
<span className="absolute inset-0 grid place-items-center bg-black/30 opacity-0 transition duration-500 group-hover:opacity-100 group-focus-within:opacity-100 [@media(hover:none)]:bg-transparent [@media(hover:none)]:opacity-100"><span className="grid h-16 w-16 place-items-center rounded-full bg-bone text-ink"><Icon n={cur?'pause':'play'} s={22}/></span></span></button>
<span aria-hidden className="mt-4 block h-px origin-left scale-x-0 bg-cyan transition-transform duration-700 group-data-[sel=true]:scale-x-100"/>
<div className="mt-3 opacity-75 transition duration-500 group-hover:opacity-100 group-data-[sel=true]:opacity-100"><h3 className="font-display text-xl font-semibold tracking-tight">{t.title}</h3><p className="text-sm text-bone/60">{t.artist}</p><p className="mt-2 flex items-center gap-2 text-xs text-bone/60">{cur&&<Eq on/>}{t.genre}{!t.src&&<span className="text-bone/60">(preview soon)</span>}<span className="ml-auto tabular-nums">{fmt(t.dur)}</span></p></div></li>})}</ul></section>}
